### ISSUE TITLE
Use of uninitialized value $name in hash element at .../Spreadsheet/ParseODS/Workbook.pm line 88

### ISSUE THREAD

**Issue by shawnlaffan** [Corion/Spreadsheet-ReadSXC#3]
I see the above warning when parsing an ods file that has been downloaded from Google Sheets.  

It would seem that there is no active sheet in the settings, and that the ```get_active_sheet``` method does not check that the ```active_sheet_name``` method returns a valid value.  

The file is otherwise imported correctly.  

I would upload an example file, but unfortunately the GitHub issue tracker does not support it.  I can share a link to that sheet if that is useful.

**Comment by Corion** [comment]
If you can provide a link to such a file, that would be great! Ideally, it is a file that I can download and put into the test suite, so please tell me if the file is OK to share.

**Comment by shawnlaffan** [comment]
Here's a link:  https://docs.google.com/spreadsheets/d/1vDAbSUeZO1mN7ryXtPfxAKCuvjs5M4v0tifkqJRXaAA/edit?usp=sharing

It's part of the [Biodiverse test suite](https://github.com/shawnlaffan/biodiverse/tree/master/t) so is already open source.  The version linked to currently lives on a branch, but should be merged onto master shortly.

**Comment by Corion** [comment]
Thank you for reporting this issue and showing me a file to reproduce it. This should be addressed by f971828e3b4951e9bd081325ae475ccfa0752abf and on its way onto CPAN as 0.27 .

**Comment by shawnlaffan** [comment]
Updated code works for me.  

Thanks for the prompt fix.
