### ISSUE TITLE
Cannot be installed on latest Strawberry Perl because of failing PerlIO::gzip

### ISSUE THREAD

**Issue by tomk3003** [Corion/Spreadsheet-ReadSXC#6]
see [RT Ticket](https://rt.cpan.org/Ticket/Display.html?id=134364)

**Comment by Corion** [comment]
This is not a bug under the control of Spreadsheet::ReadSXC. What change do you envision?

**Comment by tomk3003** [comment]
I didn't expect a change. This was just for information.
