### ISSUE TITLE
ParseODS leaks memory

### ISSUE THREAD

**Issue by troost-c** [Corion/Spreadsheet-ReadSXC#8]
Dear maintainers,

I have found that ParseODS is apparently leaking memory. If you loop over opening the same ods file, the internal perl memory usage will go up each time parseODS is called, even though all objects should be destroyed when going out of scope at the end of each loop instance. (This happens both when ParseODs is called directly and when it is called via Spreadsheet::Read.)
This is very problematic when importing bunches of ods files, as the program will finally run out of memory.

I cross-checked using Spreadsheet::Read for importing XLSX and it does not happen when importing xlsx files: Memory usage goes up in the first and second instance, but remains constant thereafter.

I suspect there is a circular reference somewhere within the workbook, e.g. between workbooks and sheets.

I attached example files and memory usage output.

[sr_test.pl.txt](https://github.com/Corion/Spreadsheet-ReadSXC/files/7136039/sr_test.pl.txt)
[sr_test.log](https://github.com/Corion/Spreadsheet-ReadSXC/files/7135985/sr_test.log)
[test.ods](https://github.com/Corion/Spreadsheet-ReadSXC/files/7135986/test.ods)
[test.xlsx](https://github.com/Corion/Spreadsheet-ReadSXC/files/7135987/test.xlsx)

System: 5.4.0-81-generic #91~18.04.1-Ubuntu SMP
perl : v5.26.1
Spreadsheet-ReadSXC 0.34 from CPAN

Best,
Christian

**Comment by Corion** [comment]
Thank you very much for the report!

This is caused by a circular reference hidden through a `XML::Twig` callback. I've weakened the reference in `parse()` and will release the fix soon to CPAN.

**Comment by troost-c** [comment]
Great! Many thanks! That was quick. 

I got the fix in 0.35  from CPAN and it solves the issue for me, too.
