### ISSUE TITLE
Ancient dates

### ISSUE THREAD

**Issue by Username-felix-is-not-available** [Corion/Spreadsheet-ReadSXC#9]
Dear maintainers,
Thank you for the great module. I am frequently using [Spreadsheet::Read](https://metacpan.org/pod/Spreadsheet::Read) which internally uses your module.
I noticed a strange behavior when parsing an *.ods file that contains ancient dates. For example, a date like 1111-11-11 from the spreadsheet is output as 1111-11-**18**. However, dates like 1919-11-19 are output correctly.
Below, I put a minimal example that prints the sheet reference. You can see that in the case of 1111-11-11, the value for the 'value' key is different than the value for the 'unformatted' key. This did not happen for the other dates that were parsed as expected.
Have a nice day,
Felix

```
#!/usr/bin/env perl

use strict;
use warnings;

use Data::Dumper;
use Spreadsheet::ReadSXC;

my $file = "./minExample.ods";

my $parser = Spreadsheet::ParseODS->new(line_separator => "\n",);
my $workbook = $parser->parse($file);
my $sheet = $workbook->worksheet('Sheet1');

print Dumper($sheet);
```
[minExample.ods](https://github.com/Corion/Spreadsheet-ReadSXC/files/10448092/minExample.ods)

**Comment by Corion** [comment]
This is a bug (or peculiarity) with the `ods` file itself. The XML in `content.xml` has:

```xml
<table:table-row table:style-name="ro1">
<table:table-cell office:value-type="date" office:date-value="1111-11-18" calcext:value-type="date">
<text:p>1111-11-11</text:p>
</table:table-cell>
</table:table-row>
```

... and the module picks the `office:date` value instead of the text, as the text can have formatting applied to it.

**Comment by Username-felix-is-not-available** [comment]
Thank you for your reply. That's weird behavior from the ods file.
Have a nice day,
Felix
